# Generated by Django 6.0.3 on 2026-03-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desejo',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desejo',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
