# Generated by Django 6.0.3 on 2026-03-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_desejo_data_aquisicao_desejo_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('consumivel', 'Consumível')], default='normal', max_length=20),
        ),
    ]
