# Generated by Django 6.0.3 on 2026-03-18 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tipo',
        ),
        migrations.CreateModel(
            name='Consumivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField(default=1)),
                ('quantidade_minima', models.IntegerField(default=1)),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.divisao')),
            ],
        ),
    ]
