# Generated by Django 6.0.3 on 2026-03-18 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_item_tipo_consumivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='consumivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.consumivel'),
        ),
    ]
