# Generated by Django 6.0.3 on 2026-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_compra_consumivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumivel',
            name='loja',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consumivel',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
