# Generated by Django 6.0.3 on 2026-03-19 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_consumivel_loja_consumivel_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('loja', models.CharField(max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('consumivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='inventory.consumivel')),
            ],
        ),
    ]
