# Generated by Django 6.0.3 on 2026-03-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_historicocompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desejo',
            name='data_aquisicao',
        ),
    ]
