# Generated by Django 6.0.3 on 2026-08-23 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_desejo_data_aquisicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicocompra',
            name='consumivel',
        ),
        migrations.AlterModelOptions(
            name='consumivel',
            options={'ordering': ['nome', 'id']},
        ),
        migrations.AlterModelOptions(
            name='desejo',
            options={'ordering': ['nome', 'id']},
        ),
        migrations.AlterModelOptions(
            name='divisao',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nome', 'id']},
        ),
        migrations.RemoveField(
            model_name='consumivel',
            name='loja',
        ),
        migrations.RemoveField(
            model_name='consumivel',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='consumivel',
            name='quantidade_minima',
        ),
        migrations.AddField(
            model_name='consumivel',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consumivel',
            name='quantidade_compra',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='consumivel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consumivel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='consumivel',
            name='divisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumiveis', to='inventory.divisao'),
        ),
        migrations.AlterField(
            model_name='consumivel',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='HistoricoCompra',
        ),
    ]
